
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KL1917
 */
public class FormAdministracion extends javax.swing.JFrame {

    ArrayList<Usuarios> arrayUsuarios;
    ArrayList<registros> arrayMisRegistros;
    ArrayList<producto> arrayProductos;
    ArrayList<String> arrayHorasCogidas;
    ArrayList<String> arrayHoras;
    Usuarios conectado;
    /**
     * Creates new form FormAdministracion
     */
    public FormAdministracion() {
        initComponents();
    }
    public FormAdministracion(ArrayList<String> horascogidas, ArrayList<String> horas, 
                                ArrayList<registros> misregistros, ArrayList<Usuarios> usuarios, 
                                            ArrayList<producto> productos,  Usuarios conected ) {
        initComponents();
        arrayMisRegistros = misregistros;
        arrayProductos = productos;
        arrayUsuarios = usuarios;
        arrayHorasCogidas = horascogidas;
        arrayHoras = horas;
        conectado = conected;
        
        if (conected.isAdmin() == true){
            btnmodificar.setEnabled(false);
            btnatender.setEnabled(false);
        }
        else{
            btnalta.setEnabled(false);
            btnbaja.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnalta = new javax.swing.JButton();
        btnbaja = new javax.swing.JButton();
        btnatender = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnvercitas = new javax.swing.JButton();

        btnalta.setBackground(new java.awt.Color(204, 204, 204));
        btnalta.setText("Alta Trabajador");
        btnalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltaActionPerformed(evt);
            }
        });

        btnbaja.setBackground(new java.awt.Color(204, 204, 204));
        btnbaja.setText("Baja Trabajador");
        btnbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbajaActionPerformed(evt);
            }
        });

        btnatender.setBackground(new java.awt.Color(204, 204, 204));
        btnatender.setText("Atender");
        btnatender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatenderActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(204, 204, 204));
        btnmodificar.setText("Modificar Stock");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnvercitas.setBackground(new java.awt.Color(204, 204, 204));
        btnvercitas.setText("Ver Citas");
        btnvercitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvercitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnalta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbaja, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnatender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvercitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnatender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvercitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltaActionPerformed
        FormAlta nuevaalta = new FormAlta(arrayUsuarios);
        nuevaalta.setVisible(true);
    }//GEN-LAST:event_btnaltaActionPerformed

    private void btnbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbajaActionPerformed
        FormBaja nuevabaja = new FormBaja(arrayUsuarios);
        nuevabaja.setVisible(true);
    }//GEN-LAST:event_btnbajaActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        FormModificarStock nuevomodificar = new FormModificarStock(arrayProductos);
        nuevomodificar.setVisible(true);
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnvercitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvercitasActionPerformed
        FormVerCitas nuevovercitas = new FormVerCitas(arrayMisRegistros);
        nuevovercitas.setVisible(true);
    }//GEN-LAST:event_btnvercitasActionPerformed

    private void btnatenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatenderActionPerformed
        FormAtender nuevoatender = new FormAtender(arrayMisRegistros, arrayProductos);
        nuevoatender.setVisible(true);
    }//GEN-LAST:event_btnatenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalta;
    private javax.swing.JButton btnatender;
    private javax.swing.JButton btnbaja;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnvercitas;
    // End of variables declaration//GEN-END:variables
}
